advplyr/audiobookshelf-app

- android/app/src/main/java/com/audiobookshelf/app/PlayerNotificationService.kt
- components/AudioPlayerMini.vue
- components/app/StreamContainer.vue
1. `playWhenReady` is ok now.
2. Found another problem: no “seekback” when operating with media notification.
So move the “seekback” to `onEvents() -> Player.EVENT_IS_PLAYING_CHANGED`.
Although there may be some subtle lag, but it works.
> Fix playWhenReady

- ios/App/App/AppDelegate.swift
- ios/App/App/MyNativeAudio.swift
- Fixed a bug that caused the player to always start at 0:00
- Added `UIApplication.shared.beginReceivingRemoteControlEvents()` to show a "now playing" notification
- Fixed a bug that caused the cover to not load correctly
- Added more remote transport commands
> Show "now playing" on lock screen & in control center

- ios/App/App/MyNativeAudio.swift
- Covers don't get fetched every time the metadata is updated
- Seeking/playing/pausing are handled correctly
If you are wondering, the method returned when the player wasn't playing, which resulted in funny things happening when you seek/play/pause. I also added a `seek` method, which updated the MP-state
> Massively improved the MPNowPlayingInfoCenter

- pages/search.vue
Book and podcast IDs are nested inside the libraryItem returned by the API. The search feature was broken for books and podcasts as it tried to reference an undefined ID, this just fixes the ID grabbing from the returned results.
> Fix Book/Podcast Search

- components/connection/ServerConnectForm.vue
As mentioned in [a discussion](https://github.com/advplyr/audiobookshelf-app/discussions/60#discussioncomment-2601321) there seems to be an issue occasionally with being unable to ping the server on cellular data, and the probable cause is the 1 second timeout. Does 3 seconds sound like a good number instead?
> Increase server ping timeout

- pages/bookshelf/index.vue
Instead of displaying "Bookshelf empty for library ____" while the app is awaiting a response on opening the Home bookshelf, use ui-loading-indicator to indicate data is being fetched. Fixes #53.
> Loading indicator while awaiting library

- ios/App/App/plugins/AbsAudioPlayer.swift
This isn't a good implementation of the idea, but allowing some form of swipe back gesture would be helpful for user experience to not reach for the back button. Maybe we could make this a dedicated plugin to enable and disable the gesture on item pages and disable elsewhere, as swiping back to previous library pages isn't very intuitive, but that makes this improvement exponentially more complex. I'll tinker with making it a plugin, [this](https://github.com/diiiary/capacitor-plugin-ios-swipe-back) already exists but hasn't been updated in 3 years and calls deprecated methods. At this point I just threw a line in the middle of the AudioPlayer plugin to make it work.
> Enable swipe gesture to go back

- android/app/src/main/java/com/audiobookshelf/app/data/AudioProbeResult.kt
It appears that sometimes `ffprobe` can return a NULL value for the `format.tags` field when scanning files. This causes the Android app to crash when scanning local media folders.
Example FFProbe response:
```
{
"streams": [
{
"index": 0,
"codec_name": "mp3",
"codec_long_name": "unknown",
"codec_type": "audio",
"codec_tag_string": "[0][0][0][0]",
"codec_tag": "0x0000",
"sample_fmt": "fltp",
"sample_rate": "22050",
"channels": 1,
"channel_layout": "mono",
"bits_per_sample": 0,
"r_frame_rate": "0\/0",
"avg_frame_rate": "0\/0",
"time_base": "1\/14112000",
"start_pts": 0,
"start_time": "0.000000",
"duration_ts": 445606502544,
"duration": "31576.424500",
"bit_rate": "32000",
"disposition": {
"default": 0,
"dub": 0,
"original": 0,
"comment": 0,
"lyrics": 0,
"karaoke": 0,
"forced": 0, …
```
> Handle audio probes that don't return any tags

- components/app/SideDrawer.vue
This commit adds the server version next to the URL. It also adds a new style to ensure that the text wraps properly if the URL is too long. Trying text-wrap didn't work for whatever reason.
Screenshots of the textwrap change:
before:
after:
> Show server version in drawer

- android/app/build.gradle
- android/app/src/main/java/com/audiobookshelf/app/MainActivity.kt
- android/app/src/main/java/com/audiobookshelf/app/plugins/AbsFileSystem.kt
Fixes #159 
After reading over the Simple storage docs I made some changed in the AbsFileSystem plugin to handle Access Denied to External media types by requesting the needed access from the user,  Tested this code on Android 10 and it seems to work. 
User Flow
1. Open Side Bar
2. Select Local Media
3. Choose 'Books' in dropdown and Click New Folder
4. Create the folder or select and existing one on an SD card
5. Click Allow and Allow again
6. Message dialog will appear stating Write perms are needed
7. Another Folder selector is shown at SD Card Root level
8. Click Allow and Allow again
Permission is granted but the folder is not added to the App, user will need to select the folder again, However this time the app will add the folder as expected. If the user pick the folder instead of …
> Added ability to Give write permission to the SD card

- ios/App/App/plugins/AbsAudioPlayer.swift
- ios/App/Shared/player/AudioPlayer.swift
- ios/App/Shared/player/PlayerProgress.swift
This turned out to be several problems:
1) The active session was not syncing with the server on startup, due to an assumption the player was initialized and `PlayerHandler.getPlaybackSession()` could be used
2) This lead to a scenario that when the player did sync with the server on the next sync, `seek()` was called, which was triggering playback to start
3) Upon investigation, I also found a situation where iOS being "smart" could attempt to restore playback when connecting Bluetooth headphones during app startup
4) This issue was solved by adding a guard to `play` and `pause` until the player is initialized
> Fix playback session starting sometimes on app launch

- android/app/src/main/java/com/audiobookshelf/app/data/DeviceClasses.kt
- android/app/src/main/java/com/audiobookshelf/app/player/MediaSessionCallback.kt
- android/app/src/main/java/com/audiobookshelf/app/player/PlayerConstants.kt
- android/app/src/main/java/com/audiobookshelf/app/player/PlayerNotificationService.kt
- android/app/src/main/res/values/strings.xml
- android/build.gradle
This PR adds additional media controls to Android Auto (and perhaps Wear and maybe Automotive?) I know little about how Android's MediaBrowserService works and Google's lack of documentation seems motivated to keep things a mystery.
So far, this change includes:
- Addition of jump forward button in Android Auto.
- Addition of jump back button in Android Auto.
- Player, Android notification, and Android Auto all respect the "Jump" times specified in device settings.
Discussion Points:
- Previous button - This button appears on Android Auto and I have no idea how to remove it, so I mapped it's functionality to the media player's previous functionality.
- Next button - Since it seems we have no control over which standard buttons are shown, I experimented with adding a next button as a …
> Add additional controls to android auto

- components/app/SideDrawer.vue
- ios/App/Podfile
- pages/downloads.vue
Dedicated page for visualizing and managing downloads on iOS. Currently sorted by download date. I didn't implement progress views on the covers like on the main bookshelf because it seems like that'd require a lot of modification to BookCover.vue, and since clicking on the book opens its item page you can see progress there anyways. I attempted to remove the downloads page from the side drawer/hamburger menu when there are no downloads, but I couldn't find a non-janky method for continuously checking media items. Is naming this Downloads okay? I know Android terms it Local Media, but "downloads" seems like it would be more straightforward to most users.
Screenshot:
> Downloads page for iOS

- ios/App/Shared/player/AudioPlayer.swift
I occasionally see the following error when run on my device, which does not appear on the simulator:
```
Failed to set AVAudioSession category
Error Domain=NSOSStatusErrorDomain Code=2003329396
```
It turns out the call to `AVAudioSession.sharedInstance().setCategory` does not need the `.allowAirPlay` option. That option [is only valid when the category is `.playAndRecord`](https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions/1771736-allowairplay).
I verified with this option removed AirPlay still functions, and the error is also gone.
> Fix failed set category on initAudioSession

- ios/App/App/AppDelegate.swift
- ios/App/App/plugins/AbsAudioPlayer.swift
- ios/App/App/plugins/AbsDatabase.swift
- ios/App/App/plugins/AbsDownloader.swift
- ios/App/App/plugins/AbsFileSystem.swift
- ios/App/Shared/models/PlaybackSession.swift
- ios/App/Shared/models/download/DownloadItem.swift
- ios/App/Shared/models/local/LocalLibraryItem.swift
- ios/App/Shared/models/local/LocalMediaProgress.swift
- ios/App/Shared/models/server/AudioTrack.swift
- ios/App/Shared/player/AudioPlayer.swift
- ios/App/Shared/player/PlayerHandler.swift
- ios/App/Shared/player/PlayerProgress.swift
- ios/App/Shared/util/ApiClient.swift
- ios/App/Shared/util/DaoExtensions.swift
- ios/App/Shared/util/Database.swift
- ios/App/Shared/util/NowPlayingInfo.swift
- ios/App/Shared/util/Store.swift
This PR refactors the iOS player sync hooks to rely on the native instead `AVPlayer` time observation hooks instead of using timers.
The theory is in low memory situations, iOS is stopping the current tick timer in the background, leading to issues where the player does not have the most accurate `currentTime`.
* Persisting a syncing sessions are now done via `addPeriodicTimeObserver()` firing every 0.5 wall-clock seconds
* The database `currentTime` is updated on every invocation
* The server receives the latest session and media progress every 10 wall-clock seconds and when the player is paused or stopped
* `timeListening` is now calculated based on `updateAt` times between sync vs. running an incremental counter each second
* This ensures it's reliable regardless of the interval the …
> Improve iOS Player Sync Logic

- ios/App/Shared/player/AudioPlayer.swift
Found a bug where the `currentTime` was not factoring in the track index when updating the playback session. This is also includes #338 to prevent a merge conflict.
> Fix: Session currentTime is inaccurate for books with multiple tracks

- ios/App/Shared/player/AudioPlayer.swift
- ios/App/Shared/player/PlayerHandler.swift
I'm seeing an occasional crash on the iOS app, which I've traced back to the playback session return nil from Realm. I'm continuing to investigate scenarios where that may happen. In the meantime, I have addressed the hard crashes by improving the error handling:
* In situations where without the playback session we could silently fail, I am allowing this to occur now
* Used for status updates, saving current progress (as if one progress updates fails, that's okay, another one will be occurring soon), etc
* In situations where a missing playback session results in a failure, I am throwing the failed playback notification
* These situations occur when first starting playback
* The user will then be allowed to retry playback
> fix: iOS app crashes when playback session not loaded from Realm

- ios/App/App/AppDelegate.swift
- ios/App/App/plugins/AbsDownloader.swift
Implements iOS background downloads. Turns out I had this 99% of the way there, and it only needed a little extra push [of reading the documentation](https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background).
This fixes #341. This also improves #344, as iOS will be smart and automatically pause and retry background downloads when network conditions are poor.
> feat: Handle iOS background downloads

- ios/App/Shared/player/AudioPlayer.swift
Fixes #350.
Note: I've observed that sometimes playback does stop when seeking. I logged this as #354. This was occurring before this PR as well. I will look at that too, but this is more important to get out the door.
> Fixes iOS player seek issues with multi-track books

- ios/App/App.xcodeproj/project.pbxproj
- ios/App/App/plugins/AbsAudioPlayer.swift
- ios/App/Shared/models/server/AudioTrack.swift
- ios/App/Shared/player/AudioPlayer.swift
- ios/App/Shared/player/AudioPlayerSleepTimer.swift
- ios/App/Shared/player/PlayerHandler.swift
This took me quite a while to figure out, but I rewrote the iOS sleep timer again to address issues with multi-track books. Fixes #351.
The iOS sleep timer now:
* Uses a `Timer` for countdown-based sleep timers
* Uses a `TimeObserver` for a scheduled chapter end time
This seems to strike the balance of accuracy, reliability, and code readability. I have tested this PR with:
* Single-track books
* Multi-track books
* Podcasts
For each media type, I have verified:
* How the timer reacts to play/pause
* How the timer reacts to changes in playback speed
* How the timer reacts to seeking
* How the timer handles seeking past the end time (in case of a chapter end timer)
Why rewrite the sleep timer again? While the previous strategy worked, it involved recalculating the stop time each time …
> Rewrite iOS sleep timer to handle multi-track files

- ios/App/Shared/player/AudioPlayer.swift
This PR addresses several issues (fixes #343):
* The active audio session is now changed to `false` when the player is paused
* This also ensures the below fixes do not trigger when the player is paused
* When an audio interruption occurs (such as Siri, directions in CarPlay, a phone call, etc), if ABS was playing before the interruption occurred, ABS will resume playback after the interruption
* The player will use the `skipBack` setting when resuming, so for long interruptions, audio will be allowed to rewind back
* If plugging in headphones, audio will continue in the headphones
* If disconnecting headphones, audio will stop playing
* There may be other scenarios we want to pause audio, but I'm not sure of them at this moment
* We now have the framework to add others in the future …
> Fix: Handle iOS audio events

- ios/App/Shared/models/local/LocalMediaProgress.swift
Fixes #348. This may actually be the fix for a few other crashes, as there could be other cases where the `LocalMediaProgress` did not have the id set.
> Fix marking local book as read crashing iOS app

- android/app/src/main/java/com/audiobookshelf/app/data/DeviceClasses.kt
- android/app/src/main/java/com/audiobookshelf/app/player/MediaSessionCallback.kt
- android/app/src/main/java/com/audiobookshelf/app/player/PlayerConstants.kt
- android/app/src/main/java/com/audiobookshelf/app/player/PlayerNotificationService.kt
- android/app/src/main/res/drawable-anydpi/skip_next_24.xml
- android/app/src/main/res/drawable-anydpi/skip_previous_24.xml
- android/app/src/main/res/drawable/skip_next_24.xml
- android/app/src/main/res/drawable/skip_previous_24.xml
- android/app/src/main/res/values/strings.xml
Control buttons in Android Auto (and probably Android Wear too) are messy. The skip back/forward buttons appears sometimes and the jump forward/back a few seconds don't show at all in minimized modes.
This PR does the following:
- Show skip buttons if multiple items are available. ![minimized](https://user-images.githubusercontent.com/1752370/188323780-a559d803-6bb7-4123-9464-74cf670ac660.png)
- Hide skip buttons when multiple queue items are not available. ![skip_hidden](https://user-images.githubusercontent.com/1752370/188323779-30ebcf3c-1c30-4677-9ee5-71ed5ee3f3c2.png)
- Show jump buttons when the app is "minimized" instead of skip buttons. ![skip_shown](https://user-images.githubusercontent.com/1752370/188323776-8b143ff7-b0ca-4c41-8ee2-895b00d05750.png)
> Cleanup Android Auto buttons

- ios/App/App.xcodeproj/project.pbxproj
- ios/App/App/AppDelegate.swift
- ios/App/App/plugins/AbsAudioPlayer.swift
- ios/App/Podfile
- ios/App/Shared/player/AudioPlayer.swift
- ios/App/Shared/player/PlayerHandler.swift
This PR addresses a few different issues related to app startup:
- Fixes a warnings related to accessing `window` too early
- Fixes a crash where a race condition can cause the AudioPlayer's rate to be modified off the main queue
- Fixes #374 by ensure if WebKit is reloaded and the native code is not, the two can get back in sync
> Fix various iOS app startup issues

- ios/App/App/plugins/AbsAudioPlayer.swift
- ios/App/Shared/player/PlayerProgress.swift
Using the `async` version of Realm on iOS 16 is resulting in incorrect thread crashes. This fix changes the async Realm calls to use the synchronized version by using a different constructor.
`Realm()` == `Realm(queue: DispatchQueue = nil)`
But when calling Realm in an async method, the code is picking up the `Realm() async` constructor, which we don't want.
By calling `Realm(queue: nil)` we force the non-async path.
> fix: iOS 16 realm crash

- ios/App/Shared/models/local/LocalLibraryItem.swift
- ios/App/Shared/player/PlayerHandler.swift
- ios/App/Shared/util/NowPlayingInfo.swift
Fixes #373. Local cover images were never being loaded and always fetched from the server, hence if the network was unavailable when playback started, the artwork would not be available.
> Fix local cover images not used on iOS

- ios/App/Shared/player/AudioPlayer.swift
- ios/App/Shared/player/PlayerHandler.swift
Fixes #368. Seek back time had three different issues:
1. Player initialization would update the session's `updatedAt` value, so anytime the player was reinitialized, we were starting fresh
2. Date math was wrong, leading always to 2 seconds of seek back time
3. Resuming playback from the UI was not allowing the seek back calculation
All three issues have been addressed in this PR.
> fix: iOS seek back time not winding back

- components/app/AudioPlayerContainer.vue
Fixes a regression introduced in #386. By allowing `onReady()` to be called multiple times in the native code, it unearthed a situation where it was being called multiple times from the UI... when the playback rate changes.
This fix ensures that `onReady()` is only fired the first time settings are loaded, not every time.
> fix: onReady called multiple times

- ios/App/App.xcodeproj/project.pbxproj
- ios/App/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme
- ios/App/AudiobookshelfUnitTests/Shared/player/util/PlayerTimeUtilsTests.swift
- ios/App/Shared/player/AudioPlayer.swift
- ios/App/Shared/player/util/PlayerTimeUtils.swift
This PR is laying the groundwork for writing Swift unit tests:
* Refactors the seek back time logic into a testable `PlayerTimeUtils` class
* Writes a set of unit tests against `PlayerTimeUtils`
* The can be run with `Test` build mode in Xcode
* Fixes a bug with the seek back logic that was discovered with the unit tests
* The `currentTime` could go negative if first starting the book
Going forward, I will be aiming to write unit tests for all code. While I expect it will take time to get everything tested, I want to start somewhere!
Expect some additional PRs in the future, but not immediately:
* Adding the ability to run the unit tests from the command line via npm
* A GitHub Action to automatically run the unit test suite for all PRs
> feat: Groundwork for testable iOS swift code

- ios/App/Shared/player/AudioPlayer.swift
Fixes #354.
There was a small gap during player re-initialization (which may happen if seeking to a different track in the queue) where the player was marked as initialized, but it hadn't started playing yet. This gap would allow a second seek operation (which could occur by rapidly pressing the skip button or multiple taps on the seek bar) to occur. However, since `AVPlayer` only allows once concurrent seek operation, the second seek operation would trigger a race condition where sometimes the second seek would execute before the first seek and the remaining initialization code (such as resuming playback) would never occur.
This PR fixes the issue by ensuring the player is not marked as initialized until all of the initialization code has run.
> fix: Player sometimes pauses during seek on iOS

- android/app/src/main/res/values-v21/styles.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/styles.xml
On some Samsung devices, white is used as the default color for the navigation bar in dark mode, see https://github.com/jellyfin/jellyfin-android/issues/581.
I colored the status and navigationbar with the same background color as the header of the website.
There is no issue for this PR.
> Colored status and navigationbar

- android/app/src/main/res/xml/config.xml
- ios/App/App/AppDelegate.swift
- ios/App/App/config.xml
- ios/App/App/plugins/AbsAudioPlayer.swift
- ios/App/App/plugins/AbsDatabase.swift
- ios/App/Podfile
- ios/App/Shared/models/DeviceSettings.swift
Prevents the app's webview from allowing a scroll of the actual app body, as per issue [#5907](https://github.com/ionic-team/capacitor/issues/5907) in the Capacitor repo. Previously the app could behave like this:
> Don't allow webview to scroll out of bounds vertically

- ios/App/Shared/player/PlayerProgress.swift
Resolves #404. The issue seems to be that the server expects that when syncing an open (streamed) session, the attribute `timeListened` to be time since the last sync to the server (as per the [API docs](https://api.audiobookshelf.org/#sync-an-open-session)). But the app uses that logic to store timeListened offline as well, so updates it cumulatively and sends that to the server where the time is compounded. This explains why the listening sessions seemed only slightly off for a few seconds of listening, but exponentially huge (thousands of hours) for longer streamed listens. This PR just adds a bit of logic to reset that timeListening attribute each time there is a server sync when the book is being streamed. I did some testing both with downloaded and local books and the listening time …
> Fix Listening Stats

- layouts/default.vue
Fixes #379 (mostly). Prevents selecting text in the app, but does not prevent long-press to download covers on iOS. Seems like an appropriate "bug" to keep as it exists on the item page?
> Prevent selecting of text in the app

- components/modals/ChaptersModal.vue
When long chapter names are being used, it may easily happen that parts of the name is cut off. If this part identifies the latest chapter name or number, it may make chapters indistinguishable from one another. This makes it near imposible to select a specific chapter if the book has many chapters.
This patch addresses the issue by starting each item in the list of chapters with an index number.
This fixes #479
> Make chapters identifiable

- pages/item/_id.vue
This patch updates the metadata table in the book details view, turning it into a CSS grid layout. This fixes a few issues with the current layout:
- Keys and values are not vertically aligned with the value being displayed a little bit above the baseline of the key.
- There is no horizontal alignment of the table columns. In fact, it is technically not a table despite the CSS being tuned to almost look like one. Just turning this into a real grid looks cleaner.
- The code for making multi-line values not wrap is broken. This fixes the problem.
This also renames “Publish Year” to “Published”. Mainly because it is shorter.
> Metadata Table Alignment

- components/app/AudioPlayer.vue
- components/modals/Dialog.vue
Instead of handling some items of the player menu as special cases, adding icons and colors, this patch allows menu items to have icons in general, allowing for the removal of the special cases.
This also makes it easy to actually use a homogeneous style for all of the player menu items, letting them all have an icon and aligning them visually.
> Make Player Menu Items Look Alike

- components/app/AudioPlayer.vue
- plugins/localStore.js
This patch allows user to not only add a chapter track but also remove the total track. This means that you can have only the total track or only the chapter track.
This patch does not allow user to have no track at all. Disabling one track will automatically enable the other one, if that one is already disabled.
The reasoning behind this is that for long-ish audiobooks, users will not very often look at the overall progress. In fact, I find the progress bar mostly useful only for quickly seeking to a position when jumping back a few seconds is not sufficient.
In the seldom occasion that I want the overall progress, I can easily get it from the book details page.
> Chapter and Total Track in Player

- ios/App/Shared/player/AudioPlayer.swift
This adds nextTrack/previousTrack handlers. I've never needed to skip entire chapters from my headphones, so the behavior is similar to skipForward/skipBackward -- only moving 5-30s in either direction.
This resolves an issue I've had where double/triple clicking AirPod Pros wouldn't change playback position.
> Handle skip track events on iOS

- pages/item/_id/index.vue
This patch fixes the separators between metadata list entries in the book detail view. Items were separated only by comma. A space was missing.
This just adds a space to both the genre as well as to the narrator separators.
> Fix Metadata List Separators

- components/app/AudioPlayer.vue
This patch moves the progress bar slightly up for a better separation between playback controls and seeking.
The reasoning behind this is that I (and probably others as well) often interact with this interface in a clumsy, half-asleep state. Due to the closeness of the progress bar and the play/pause button, I have managed it several times to accidentally seek instead of pause. That is really annoying since you then have to manually find the previous playback position again.
Long term, I would love to see more of the available space being used. In particular in the player interface. There should be enough free space available. Especially if you have just one of the progress bars active. But for now, this is just a quick-fix to improve the current situation.
> Player Progress Bar Position

- pages/item/_id/index.vue
This patch moves the discard progress functionality from the tiny icon in the top right corner of the progress display to the options menu.
The reasoning for this is that resetting progress is an option which is unlikely to be used very often and therefor does not need to be on the main screen. In addition to that, the menu already holds the related options to mark the book as finished and to discard the progress of a finished book.
Finally, this removes the tiny icon which does not really match the rest of the user interface of the app.
> Move Discard Progress to Menu

- pages/account.vue
This patch updates the account settings view, trying to make it look a bit cleaner by:
- Making the logout button look more like a button. The full width looked odd on large devices or in landscape mode.
- Removing the version number. It is already listed in the main menu anyway.
- Moving the hint about reporting bugs and the GitHub link to the bottom.
The hint is still a bit weird in this view. Maybe long-term, we want to move all these information about the app (version, issues, …) to a separate view. But that's something for another day.
> App info in account settings

- pages/item/_id/index.vue
This patch is a follow up to the discussion from #559 about potentially simplifying progress interactions.
This patch essentially reduces the interactions to two simple options which allow users to always marks books as finished or discard the progress and thus mark them as not yet started with a single interaction:
- If users have already listed to the book, regardless of the state of the progress (finished, halfway through, …), they get an option to discard the progress. This replaces the additional “mark as not finished” option, but it should still be clear to users what happens.
- If a book is not yet finished, regardless of the state of the progress (not yet started, halfway through), users get a “mark as finished” option which sets the progress to 100%.
This is hopefully a bit …
> Simplify progress (re)sets

- pages/item/_id/index.vue
This patch adds icons similar to those used in other app menus to the book details menu.
This is based on pull request #561 and needs to be slightly adjusted if that one is not merged.
> Icons for book details menu

- components/modals/Dialog.vue
This patch slightly increases the padding for menu dialogs. No real reason for this except that I like the look of this better ;-)
> Increase padding for menus

- package-lock.json
Running `npm ci` you always get a warning about an old lock-file format being used:
```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
```
This patch simply re-generates the file by removing the old one and running`npm install`. That gets rid of the warning.
> Re-generate lock file

- ios/App/App/Info.plist
As discussed on Discord, and tested as far as having Apple approve the bundle.
Just disable ATS.
https://testflight.apple.com/join/5Nf8O3mI for the approved build.
https://github.com/advplyr/audiobookshelf-app/issues/538 for related issue.
https://developer.apple.com/forums/thread/3544 for related response from Apple making it sound this is acceptable.
> Disable ATS for iOS

- components/covers/BookCover.vue
- pages/item/_id/index.vue
This patch adds a heavily blurred version of the cover image as background to the cover image area in the book details.
This looks especially nice on larger devices like tablets.
> Blur Cover Image Background

- pages/item/_id/index.vue
This patch improves word wrapping for the description text in book details by justifying the text block and allowing for words to be wrapped by automatically inserting hyphens if necessary.
This causes the description box to look far less ragged on the right edge which I think helps the overall cleanliness of the look.
Unfortunately the app's/browser's aren't as good as e.g. the TeX algorithm for hyphening and there are JavaScript libraries which seem to reimplement that. But this is already a significant step up and far less work for something which is not the main focus of this app.
> Improve word wrapping

- store/user.js
Clicking on “logout”, you get the following TypeError:
```
TypeError: state.user is null
getUserBookmarksForItem user.js:38
bookmarks AudioPlayerContainer.vue:45
VueJS 4
render AudioPlayerContainer.vue:11
VueJS 13
logout user.js:115
wrappedMutationHandler vuex.esm.js:844
commitIterator vuex.esm.js:466
commit vuex.esm.js:465
_withCommit vuex.esm.js:624
commit vuex.esm.js:464
boundCommit vuex.esm.js:409
_callee$ account.vue:67
tryCatch pdf_viewer.js:1329
invoke pdf_viewer.js:1502
defineIteratorMethods pdf_viewer.js:1372
Babel 10
logout account.vue:56
VueJS 4
click Btn.vue:65
VueJS 33
client.js:103
```
This patch fixes the problem by checking for `null` values.
> Fix TypeError on Logout

- pages/account.vue
The account setting list the connection name which is the server address directly followed by the username. This is then followed by a field repeating the username again.
This duplication of information is nor really helpful, which is why this patch replaces this with two fields containing just the two information: host address and username.
> Account Setting Information

- components/app/AudioPlayerContainer.vue
- pages/bookshelf/index.vue
This patch implements a generic way of re-opening the player for the book you last listened to. This is especially handy when first opening the app and you can restart playback with a single click.
The player is opened only if no other book is already open in the player. It will not overwrite or replace playbacks or player already in progress.
The player is opened paused. No automatic playback since that could be really annoying.
This closes #494
https://user-images.githubusercontent.com/1008395/218283320-511981e5-26ea-4ab2-a74b-ed8aaac743a9.mp4
> Easy way to play current audiobook

- .github/testing-page-template.html
- .github/workflows/deploy-apk.yml
This page automatically builds the Android app from the latest commit on the branch master, generates a test page and publishes it to GitHub Pages as a nice way for non-developers to get the latest app version for testing without having to build it themselves.
This page might need the pages source set to GitHub Actions at Settings → Pages → Build and deployment → Source.
> Publish Android Test Page

- .github/workflows/build-apk.yml
- .github/workflows/deploy-apk.yml
This patch removes a few restriction about when the Android build workflows run. In particular, we want to run workflows…
- If the workflows themselves change because that could mean that the output changes.
- If the deployment page template changes because that would mean that the published page needs to be updated.
We could still exclude a few specific files if we wanted to, but they should rarely change and it's probably not worth the effort of keeping those lists updated.
> Build APK on Workflow Change

- android/app/src/main/AndroidManifest.xml
Closes #227
This fix was suggested [here](https://github.com/google/ExoPlayer/issues/7354#issuecomment-627811740) in the ExoPlayer repo and completely solves the issue for me. The `android:largeHeap="true"` line also seems to be in the main ExoPlayer demo code.
> Add `android:largeHeap="true"` to `AndroidManifest.xml`

- pages/item/_id/index.vue
Seems that the space still is missing before comma for the 'Authors' field. I believe it ought to have been a part of https://github.com/advplyr/audiobookshelf-app/commit/dd91bc666792f9ebaea6de2bb9c272cb38f0cd58 that fixes #777 🙂 
Also cleans up an inconsistency in what was used as `key` for the separator-`span`.
> Add missing space for authors as well #777

- pages/item/_id/index.vue
This patch fixes a small problem with the separator between several authors which is `Author A , Author B`, but should be instead `Author A, Author B` like with the other metadata fields.
> Fix separator between authors

- android/app/capacitor.build.gradle
- android/app/src/debug/res/values/strings.xml
- android/app/src/main/assets/capacitor.plugins.json
- android/app/src/main/res/values/strings.xml
- android/capacitor.settings.gradle
- components/connection/ServerConnectForm.vue
- ios/App/App/Info.plist
- ios/App/Podfile
- ios/App/Podfile.lock
- package-lock.json
- package.json
- plugins/init.client.js
This PR Provides oauth2 support
It works out-of-the-box with the current changes in https://github.com/advplyr/audiobookshelf/pull/1636
* Fully works on iOS and Android
* ~~Should work on Android, too. But needs testing (I dont have an dev env for that)~~ (Testing done successfully)
* It should - in theory - also work with Google and co, but needs testing. If there is a error I would check if the callback URLs are correct as first step
It works this way:
1. oauthRequest
* API request to `audio.example.com/auth/openid`
* This will try to redirect to the idp/authentik. Instead of redirecting Im catching it and open this link in a browser. Also Im patching the redirect_uri parameter to `&redirect_uri=audiobookshelf://oauth` 
* Also what its very important (and required by passport - oauth …
> OAuth2 Support

- ios/App/Shared/player/AudioPlayer.swift
When we seek into a different chapter, we will have to reset the progress of the current one before seeking to the new one.
> Fix track skipping on iOS (Fixes #686)

- components/connection/ServerConnectForm.vue
Also:
- Add client_id with the name of the app (for possible future use)
- Add response_type simply to provide all required oauth2 parameters for reference
- For the URL to be opened in Browser: Forward the callback/redirect_uri URL provided by the server
- Use a hardcoded variable for HTTPS enforcement, for easier debugging
> SSO: Add redirect_uri to oAuth auth request

- ios/App/Shared/player/AudioPlayer.swift
This is just the code from the comments of #622—credit to @KaiStarkk! I ran it on my device and it seems to be working normally, though I don't have old enough headphones to test the actual toggle route. Though if you sideload the APK this PR generates, you might be able to do so. Should, in all theory, work.
> Add togglePlayPauseCommand route to iOS

- ios/App/Shared/player/AudioPlayer.swift
In further testing I found a rare case where `self` was not initialized when force unwrapping in the player, causing a runtime crash.
This is now fixed, first `self `is captured weakly using `guard let`, to avoid a strong reference cycle, and then safely unwrapped to a `strongSelf `constant. If `self `is `nil `when the closure is called, it will return `.commandFailed `and exit the closure, avoiding a crash. If `self `is not nil, it will proceed as per PR #1005.
Wasn't expecting self to ever be cleaned up by the memory manager, but it appears it's possible.
[Referenced info on ARC](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/)
> [Fix] Prevent crash from force unwrapping nil value in PR-1005

- ios/App/Shared/player/AudioPlayer.swift
- ios/App/Shared/util/NowPlayingInfo.swift
When rate and default rate don't match, third party apps (e.g. Bose Music) can mistake current status as scrubbing (and disable playback controls until the two match, which currently never happens in ABS until the user changes the playback rate back to 1).
Fixes #1177
> Update Now Playing info with correct default rate.

- ios/App/App.xcodeproj/project.pbxproj
- ios/App/Shared/player/AudioPlayer.swift
- ios/App/Shared/player/AudioPlayerRateManager.swift
- ios/App/Shared/player/AudioPlayerSleepTimer.swift
- ios/App/Shared/player/DefaultedAudioPlayerRateManager.swift
- ios/App/Shared/player/LegacyAudioPlayerRateManager.swift
- ios/App/Shared/player/PlayerHandler.swift
- ios/App/Shared/util/NowPlayingInfo.swift
This is a first of two steps to implement the new (iOS 16+) rate management api in ABS.
A follow-up PR will implement the new rate manager.
FYI: I made this a downstream PR after #1178 rather than detangling them, but if there's good reason to keep them completely separate I can do so.
> Refactor AudioPlayer to use a Rate Manager protocol.

- pages/item/_id/_episode/index.vue
Here's the corrected text for your pull request:
Several podcast apps, such as Overcast and Pocket Cast, have a feature that detects Time Markers in the episode description. This feature provides a way to jump directly to that time. It's very similar to chapters, but the time markers aren't embedded in the files; they are automatically detected from the description.
This PR adds support for detecting time markers in the AudioBookShelf app as well.
The detector identifies time markers in multiple formats (at least minutes and seconds):
```
H:M:SS
H:MM:SS
HH:MM:SS
H:M:SS
```
----
Demo
https://github.com/advplyr/audiobookshelf-app/assets/814828/431ea9b9-2a5f-4b09-aac8-29dc4349c31b
> feat: Add Time Marker Detection in Episode Descriptions

- .github/workflows/i18n-check.yml
This PR updates the localization workflow to `1.3.0`. This version removes the unused copying of keys to speed up the workflow, and changes the alphabetical check to be case sensitive to conform to Weblate.
> Update i18n workflow to 1.3.0

- .github/workflows/close-issues-on-release.yml
Adds workflow to close issue automatically on release. Same as https://github.com/advplyr/audiobookshelf/pull/3208
> Add: workflow to automatically close issues on release

- pages/media/_id/history.vue
Simple change to split groups of save history items when the status for items in a group changes.
I noticed that the status (icon) was only showing for the first item in a group, if there were say 150 saves and the last 30 failed then it would still show success.
Example of the changes:
> split groups of save history items that have different status results

- android/app/src/main/java/com/audiobookshelf/app/player/PlayerNotificationService.kt
Addressing issue #141
Call setIconBitmap instead of setIconUri if book is local (bitmap is not null)
> Do not call setIconBitmap instead of setIconUri if book is local

- components/app/AudioPlayer.vue
- pages/item/_id/index.vue
- store/index.js
#1359 fixed things only for Android app. Capacitor Network plugin only shows iOS device connected if internet access is available. This fix allows iOS users to use local server without internet access. Socket is used to detect if connection to server is availabe.  networkConnected is only used for add server form and cellular permission check.
Cellular permissions for download and streaming wont work for iOS if device is connected to cellular, but without internet access to server that is used for connectivity check.
> iOS devices have always networkConnected status true

- android/app/src/main/java/com/audiobookshelf/app/data/LocalLibraryItem.kt
- android/app/src/main/java/com/audiobookshelf/app/plugins/AbsAudioPlayer.kt
This should fix #105 . This wont work 100% with books that have multiple books. 
If there is way to know how many files there should be then this can easily be extended for multi file books.
> Ensure that there is files available before playing local content

- components/connection/ServerConnectForm.vue
- plugins/capacitor/AbsAudioPlayer.js
- plugins/server.js
- store/globals.js
This adds support for connecting to servers with subdirectory, e.g. `https://my.server.com/audiobookself`.
This is the last step in preparing for subdirectory support, based on [the proposed plan](https://github.com/advplyr/audiobookshelf/discussions/3535).
The required changes include:
- Allow paths when specifying the server address in the Connect form
- Fix `this.player.src` in `AbsAudioPlayer.js` (all other changes in this file are due to formatting)
- Connect to the correct WebSocket path
- Fix `getLibraryItemCoverSrc` and `getLibraryItemCoverSrcById` in `globals.js`
I tested this using the web client, as well as on my Android phone against a server running with `RouterBasePath=/audiobookshelf` (which should support both subdirectory and non-subdirectory access). 
- I connected using …
> Support servers with subdirectory

- components/tables/podcast/EpisodesTable.vue
[Industry convention](https://help.simplecast.com/hc/en-us/articles/21953604877213-The-Difference-Between-Serial-and-Episodic-Podcasts) is that "The serial format arranges podcast episodes from oldest-to-newest". This one-line change sets the default sort for podcast episode list to _Pub Date (Ascending)_ instead of _Pub Date (Descending)_ if the podcast is of type `serial`.
> Sensible default sort for podcasts

- .github/workflows/build-apk.yml
- .github/workflows/deploy-apk.yml
This PR updates the Android build workflows to use `upload-artifact@v4` due to `@v3` being deprecated on January 30, 2025 (which is tomorrow at the time of this writing). The `upload-artifact` changes can be seen in this GitHub blog post: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
The `upload-pages-artifact` is also updated according to https://github.com/actions/upload-pages-artifact to ensure that is on the most up to date version. This workflow updates the page hosted at https://advplyr.github.io/audiobookshelf-app/. I wonder if we still need this page because it is not really advertised anywhere and the APK can be downloaded from the workflow itself. However, the page is very nice and looks professional, but not sure about maintaining it if …
> Build apk workflow update

- android/app/src/main/java/com/audiobookshelf/app/device/DeviceManager.kt
This PR cleans up the `DeviceManager.kt` file.
- No functional changes were made
- Code was autoformatted
- Javadoc-style comments were added
- Some syntax cleanup, particularly in the default device settings
- Fixed `autoSleepTimerStartTime` being set twice instead of `autoSleepTimerEndTime`
Tested on Android 15 with a Pixel 6a. I did not test with downgrading and upgrading the versions.
> Andriod `DeviceManager.kt` cleanup

- android/app/src/main/java/com/audiobookshelf/app/managers/SleepTimerManager.kt
This PR continues to clean up the Android sleep timer, and fixes an issue introduced by my first PR for cleaning up the sleep timer (https://github.com/advplyr/audiobookshelf-app/pull/1453).
Fixes https://github.com/advplyr/audiobookshelf-app/issues/1463 (first commit)
Partially fixes https://github.com/advplyr/audiobookshelf-app/issues/1097 (second commit)
Fixes https://github.com/advplyr/audiobookshelf-app/issues/1047 (third commit)
The first commit adds a check of whether audio is playing or if we are in the 2 minute grace period before resetting the sleep timer due to a shake. This prevents pausing and then setting the phone down from restarting playback.
The second commit changes the threshold to go to the end of the *next* chapter to be 10 seconds away from the end of the current …
> Android Sleep Timer cleanup part 2

- android/app/src/main/java/com/audiobookshelf/app/managers/DownloadItemManager.kt
- android/app/src/main/java/com/audiobookshelf/app/managers/InternalDownloadManager.kt
This PR refactors the `DownloadItemManager.kt` and `InternalDownloadManager.kt` by:
- Adding comments to functions
- Applying autoformatting
- Refactoring functions into smaller functions to make reuse and replacement simpler
- Increases the cache size for writing internal files from the `InputBufferStream`
- No functional changes were made
This PR is part of an effort to document files without introducing functional changes to make things a bit easier to follow.
This was tested by downloading files to both internal and external folders on a Pixel 6a running Android 15.
> Download manager cleanup

- pages/localMedia/folders/index.vue
- strings/en-us.json
This PR fixes https://github.com/advplyr/audiobookshelf-app/issues/1472 by adding an info bubble to the Local Folders. I experimented with adding the text below the folder list, but I couldn't get it to look right with a "more info" link.
The confusion can mostly be seen in the following issues (some from before support was removed). Scanning local media is also asked about relatively often on Discord, but not too frequently.
- https://github.com/advplyr/audiobookshelf-app/issues/1362
- https://github.com/advplyr/audiobookshelf-app/issues/827
- https://github.com/advplyr/audiobookshelf-app/issues/810
> Add description for local folder usage

- components/app/Appbar.vue
- components/app/AudioPlayer.vue
This PR fixes https://github.com/advplyr/audiobookshelf-app/issues/1276. Only the frontend was changed.
App bar without casting
App bar while casting
Player while casting
This was tested on a Pixel 6a using Android 15.
> Use `cast-connected` icon instead of green icon

- .github/ISSUE_TEMPLATE/bug_report.yml
This PR adds a question to beginning of the bug report form to ask users to check the `awaiting-release` tag, along with a link.
> Add question to confirm they have checked for awaiting release

- .github/ISSUE_TEMPLATE/bug_report.yml
Fixes a typo on the validation and updates the dropdown options to use strings to avoid a warning on GH.
> Fix: validation and strings for options

- ios/App/App/AppDelegate.swift
- ios/App/App/plugins/AbsDatabase.swift
- ios/App/Shared/models/DeviceSettings.swift
- ios/App/Shared/player/AudioPlayer.swift
- ios/App/Shared/player/AudioPlayerSleepTimer.swift
- pages/settings.vue
This addresses issue #831 to bring additional parity to the iOS app.
Playback will start to fadeout during last 60 seconds of the sleep timer. Once faded out, playback will be paused, volume reset, and playback seeked to start of fadeout.
> IOS: Add support for fading out on sleep timer end

- components/modals/OrderModal.vue
- components/tables/podcast/EpisodeRow.vue
- components/tables/podcast/EpisodesTable.vue
Hi there,
this PR basically just adds the recently introduced feature "[new sort option for podcasts view](https://github.com/advplyr/audiobookshelf/pull/4030)" from the webapp to the mobile app.
I tested this with my running ABS server instance and the Android emulator.
Thanks a lot for offering this great piece of open-source software!
I :heart: ABS. :smile: 
---
---
> sort podcasts by filename; display filename in table row

- android/app/src/main/java/com/audiobookshelf/app/managers/InternalDownloadManager.kt
Fixes https://github.com/advplyr/audiobookshelf-app/issues/1553.
@nichwall pointed me in the correct direction for a fix. I've tested this against my server through a reverse proxy with gzip and without the proxy, directly to the container, both work fine. This disables compression for requests using the internal download manager client. As seen in the issue the okhttp client is sending an accept encoding for gzip by default which causes issues.
And more testing you want to do on your end?
> fix(InternalDownloadManager): add accept-encoding identity to requests

- android/app/src/main/java/com/audiobookshelf/app/data/ItemInProgress.kt
- android/app/src/main/java/com/audiobookshelf/app/server/ApiHandler.kt
Reuse Jackson ObjectMapper when rendering the "Continue" Android Auto tab.
Fixes partially #1570
Android backend-only change
I took a deeper look at the issue. The same performance problem plagues the "Recent" tab as well. I believe this is the relevant discussion in the Jackson itself:
https://github.com/FasterXML/jackson-module-kotlin/issues/69
TLDR: deserialization that uses reflection will be slow on Android on the first run because reflection itself is slow. Only when the deserializer is initialized on the first run and cached can Jackson speed up. And it does speed up, in my test, after warming-up the subsequent deserializations are over an order of magnitude faster then the first one.
This PR is just a quick bandaid that removes one of the performance bottlenecks: reuses the …
> Reuse the existing ObjectMapper

- assets/tailwind.css
- components/app/AudioPlayer.vue
- pages/settings.vue
Adds a new "Black/OLED" theme option to the UI, providing a true black background for OLED displays.
Partially resolves #1006
This affects both Android and iOS.
This change affects the frontend of the app.
This PR adds a new **Black** option to the application's UI. This theme sets the primary background and several other color variables to pure black (`rgb(0, 0, 0)`), which is highly beneficial for devices with OLED screens.
Changes involve:
* Adding a new CSS definition `html[data-theme='black']` in `assets/tailwind.css` to define the specific color variables for the black theme.
* Adding `Black` as a selectable theme option in the settings page `pages/settings.vue`.
**Note:** This PR is focused only on the OLED theme. The system theme following from issue #1006 isn't resolved. 
1. …
> Add: UI Black/OLED theme

- components/modals/BookmarksModal.vue
- components/ui/TextInput.vue
- components/ui/TextInputWithLabel.vue
When pressing create bookmark the current functionality is to focus the input and select the input value.
This update removes the autofocus and leaves the input value blank with a placeholder value.
No issue but fixes issue mentioned in PR #1611
Both android/ios
Auto-focusing and selecting the bookmark input was originally added because when using a custom bookmark note the input value had to be deleted first. By having the input text auto-selected you could start typing for a custom note or press create to use the default note.
This PR removes the need to auto-select the text in the input because the input will be empty. The only downside is the input will have to be pressed to open the keyboard to add a custom note instead of automatically opened.
If it is preferred to auto open the …
> Update create bookmark to not autofocus input and use placeholder

- components/cards/LazyListBookCard.vue
On the library list view a play button is added for book libraries. This provides an option for 1 click to play from library page for audiobooks.
Fixes #1616 for the library page
Both android & ios
> Add play button to book library list view

- android/app/src/main/java/com/audiobookshelf/app/data/PlaybackSession.kt
- plugins/capacitor/AbsAudioPlayer.js
Transcoding on Android causes a server crash because it is using the direct play endpoint instead of the hls endpoint. This update uses the correct URL for HLS.
Fixes #1635
Android
A separate bug with podcast episodes was found due to this https://github.com/advplyr/audiobookshelf/pull/4520
> Fix track URL used for transcodes on Android #1635
